// src/app/layout.tsx
import './globals.css'; // Importando o CSS global

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ height: '100%', overflowY: 'auto' }}>
        {children}
      </body>
    </html>
  );
}
