name: Auto PR Release → Main

on:
  push:
    branches:
      - "release/*"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Verificar se já algum PR release/x.x.x Aberto
        id: check_pr
        run: |
          if gh pr list --base main --head "${GITHUB_REF_NAME}" --state open --json number --jq '.[0].number' | grep -q '^[0-9]\+'; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Criar PR se não existir
        if: steps.check_pr.outputs.pr_exists == 'false'
        run: |
          gh pr create \
            --base main \
            --head "${GITHUB_REF_NAME}" \
            --title "Merge ${GITHUB_REF_NAME} into main" \
            --body "🚀 Este PR foi criado automaticamente para mesclar a branch **${GITHUB_REF_NAME}** na **main**. Favor revisar e aprovar."
